# Generated by Django 4.0.4 on 2022-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbcLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=55, null=True)),
                ('action_used_on', models.CharField(blank=True, max_length=55, null=True)),
                ('changed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abc_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_address', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'client_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('client_name', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=12, null=True)),
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'client_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=40, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=40, null=True)),
                ('max_item_capacity', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=40, null=True)),
                ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(blank=True, max_length=40, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=40, null=True)),
                ('max_num_resources', models.IntegerField(blank=True, null=True)),
                ('current_num_resources', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=40)),
                ('primary_key', models.IntegerField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
    ]
