# Generated by Django 4.0.4 on 2022-04-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_address', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'client_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(blank=True, max_length=40, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=40, null=True)),
                ('max_num_resources', models.IntegerField(blank=True, null=True)),
                ('current_num_resources', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=40)),
                ('primary_key', models.IntegerField(blank=True, null=True)),
                ('isdeleted', models.IntegerField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ClientContacts',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
